Try and Catch:
- The try-catch statement consists of a try block followed by one or more catch clauses, which specify handlers for different exceptions.
- A throw statement can be used in a catch block to re-throw the exception that is caught by the catch statement.
  
For throw:
![image](https://user-images.githubusercontent.com/77484700/233782771-53ba77a8-d569-4b05-99bf-e51a0fce8863.png)

- Exception class is the base class for all exceptions.
Catch(Exception e)

Different exceptions:
![image](https://user-images.githubusercontent.com/77484700/233782810-a38b09b3-7a56-4e02-81b3-6a88afc13a6a.png)


The finally statement lets you execute code, after try...catch, regardless of the result.

